import pygame

pygame.init()

old_freddy = [pygame.image.load('gifs/old_freddy/old_freddy1.png'),
              pygame.image.load('gifs/old_freddy/old_freddy2.png'),
              pygame.image.load('gifs/old_freddy/old_freddy3.png'),
              pygame.image.load('gifs/old_freddy/old_freddy4.png'),
              pygame.image.load('gifs/old_freddy/old_freddy5.png'),
              pygame.image.load('gifs/old_freddy/old_freddy6.png'),
              pygame.image.load('gifs/old_freddy/old_freddy7.png'),
              pygame.image.load('gifs/old_freddy/old_freddy8.png'),
              pygame.image.load('gifs/old_freddy/old_freddy9.png'),
              pygame.image.load('gifs/old_freddy/old_freddy10.png'),
              pygame.image.load('gifs/old_freddy/old_freddy11.png'),
              pygame.image.load('gifs/old_freddy/old_freddy12.png'),
              pygame.image.load('gifs/old_freddy/old_freddy13.png'),
              pygame.image.load('gifs/old_freddy/old_freddy14.png'),
              pygame.image.load('gifs/old_freddy/old_freddy15.png')]

old_bonnie = [pygame.image.load('gifs/old_bonnie/old_bonnie1.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie2.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie3.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie4.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie5.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie6.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie7.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie8.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie9.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie10.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie11.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie12.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie13.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie14.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie15.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie16.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie17.png'),
              pygame.image.load('gifs/old_bonnie/old_bonnie18.png')]

old_chica = [pygame.image.load('gifs/old_chica/old_chica1.png'),
             pygame.image.load('gifs/old_chica/old_chica2.png'),
             pygame.image.load('gifs/old_chica/old_chica3.png'),
             pygame.image.load('gifs/old_chica/old_chica4.png'),
             pygame.image.load('gifs/old_chica/old_chica5.png'),
             pygame.image.load('gifs/old_chica/old_chica6.png'),
             pygame.image.load('gifs/old_chica/old_chica7.png'),
             pygame.image.load('gifs/old_chica/old_chica8.png'),
             pygame.image.load('gifs/old_chica/old_chica9.png'),
             pygame.image.load('gifs/old_chica/old_chica10.png'),
             pygame.image.load('gifs/old_chica/old_chica11.png')]

old_foxy = [pygame.image.load('gifs/old_foxy/jumpscare/old_foxy1.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy2.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy3.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy4.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy5.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy6.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy7.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy8.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy9.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy10.png')]