import pygame

pygame.init()

old_freddy = [pygame.image.load('gifs/old_freddy/jumpscare/old_freddy1.png'),
              pygame.image.load('gifs/old_freddy/jumpscare/old_freddy2.png'),
              pygame.image.load('gifs/old_freddy/jumpscare/old_freddy3.png'),
              pygame.image.load('gifs/old_freddy/jumpscare/old_freddy4.png'),
              pygame.image.load('gifs/old_freddy/jumpscare/old_freddy5.png'),
              pygame.image.load('gifs/old_freddy/jumpscare/old_freddy6.png'),
              pygame.image.load('gifs/old_freddy/jumpscare/old_freddy7.png'),
              pygame.image.load('gifs/old_freddy/jumpscare/old_freddy8.png'),
              pygame.image.load('gifs/old_freddy/jumpscare/old_freddy9.png'),
              pygame.image.load('gifs/old_freddy/jumpscare/old_freddy10.png'),
              pygame.image.load('gifs/old_freddy/jumpscare/old_freddy11.png'),
              pygame.image.load('gifs/old_freddy/jumpscare/old_freddy12.png'),
              pygame.image.load('gifs/old_freddy/jumpscare/old_freddy13.png'),
              pygame.image.load('gifs/old_freddy/jumpscare/old_freddy14.png'),
              pygame.image.load('gifs/old_freddy/jumpscare/old_freddy15.png')]

old_bonnie = [pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie1.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie2.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie3.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie4.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie5.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie6.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie7.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie8.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie9.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie10.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie11.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie12.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie13.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie14.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie15.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie16.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie17.png'),
              pygame.image.load('gifs/old_bonnie/jumpscare/old_bonnie18.png')]

old_chica = [pygame.image.load('gifs/old_chica/jumpscare/old_chica1.png'),
             pygame.image.load('gifs/old_chica/jumpscare/old_chica2.png'),
             pygame.image.load('gifs/old_chica/jumpscare/old_chica3.png'),
             pygame.image.load('gifs/old_chica/jumpscare/old_chica4.png'),
             pygame.image.load('gifs/old_chica/jumpscare/old_chica5.png'),
             pygame.image.load('gifs/old_chica/jumpscare/old_chica6.png'),
             pygame.image.load('gifs/old_chica/jumpscare/old_chica7.png'),
             pygame.image.load('gifs/old_chica/jumpscare/old_chica8.png'),
             pygame.image.load('gifs/old_chica/jumpscare/old_chica9.png'),
             pygame.image.load('gifs/old_chica/jumpscare/old_chica10.png'),
             pygame.image.load('gifs/old_chica/jumpscare/old_chica11.png')]

old_foxy = [pygame.image.load('gifs/old_foxy/jumpscare/old_foxy1.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy2.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy3.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy4.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy5.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy6.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy7.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy8.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy9.png'),
            pygame.image.load('gifs/old_foxy/jumpscare/old_foxy10.png')]

baby = [pygame.image.load('gifs/baby/jumpscare/baby1.gif'),
        pygame.image.load('gifs/baby/jumpscare/baby2.gif'),
        pygame.image.load('gifs/baby/jumpscare/baby3.gif'),
        pygame.image.load('gifs/baby/jumpscare/baby4.gif'),
        pygame.image.load('gifs/baby/jumpscare/baby5.gif'),
        pygame.image.load('gifs/baby/jumpscare/baby6.gif'),
        pygame.image.load('gifs/baby/jumpscare/baby7.gif'),
        pygame.image.load('gifs/baby/jumpscare/baby8.gif'),
        pygame.image.load('gifs/baby/jumpscare/baby9.gif'),
        pygame.image.load('gifs/baby/jumpscare/baby10.gif'),
        pygame.image.load('gifs/baby/jumpscare/baby11.gif')]

springtrap1 = [pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap1.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap2.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap3.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap4.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap5.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap6.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap7.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap8.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap9.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap10.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap11.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap12.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap13.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap14.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap15.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap16.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap17.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap18.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap19.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap20.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap21.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap22.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap23.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap24.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap25.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap26.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap27.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap28.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap29.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap30.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap31.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare1/springtrap32.gif')]

springtrap2 = [pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap1.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap2.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap3.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap4.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap5.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap6.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap7.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap8.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap9.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap10.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap11.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap12.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap13.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap14.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap15.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap16.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap17.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap18.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap19.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap20.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap21.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap22.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap23.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap24.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap25.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap26.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap27.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap28.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap29.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap30.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap31.gif'),
               pygame.image.load(f'gifs/springtrap/jumpscare2/springtrap32.gif')]